# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Movie.create([ 
    {name: "Ace Of Swords", img: "Ace Of Swords", description: "A new clarity. Opening up to a new way of thinking. Figuring out a solution to a problem. Using your brain, being smart about a situation. Insight. Being careful with words & calculations. Though as a precursor to action. Realizing soe missing information. A key to making something work, perhaps an alteration of your perceptions is needed. A simple tool like a nail can create connections strong enough to build a house."},
    {name: "Two Of Swords", img: "Two Of Swords", description: "Indecision, a lack of clarity due to emotional pain. Being to self-defensive. When your desire to protect yourself causes you to build emotional walls. Acting out of distrust, not moving from a clear conscience. Projecting onto others. Not seeing things clearly, only seeing through the lens of your own personal issues. Myopic vision. Seeing others as enemies, not allies. The two hands with knivers are interconnected -- the cannot avoid hurting each other, and themselves, as long as they keep a knife in their hands. Suggests a need to retreat from drama or chaos, to re-center within yourself, to find a more loving energy."},
    {name: "Three Of Swords", img: "Three Of Swords", description: "The most iconic meaning is romantic heartbreak. Betrayal. But also, scars, holding onto emotional heartache. Allowing words to harm too deeply, allowing negative thoughts to continue to cause pain. Closing your once-open heart. A need to heal the disconnect.  A heartbreaking event can cause exponentially more pain when you hold onto it, letting it find a home inside and locking the dorr, instead of releasing it into the wild and keeping the dorr to the heart open. An echo of pain that remains long after. Scissors cutting the flower that still blooms shows how emotional pain is a natural part of life, and that how deeply it hurts us depends on how we respond to it."},
    {name: "Four Of Swords", img: "Four Of Swords", description: "Recognizing that there is a need for downtime, for recuperation. Healing that comes from within. A pause in order to recover, a hibernation to calm destructive thoughts. Quiet contemplation. Instrospection. Meditation. Needing time away. Looing for structures that enable healing. A hand with acupuncture needles and another with the acupuncture points as stars show how health resides within you and simply requires you to give it a chance to flourish. Re-aligning with the natural flows of the mind, body, and spirit."},
    {name: "Five Of Swords", img: "Five Of Swords", description: "Discord. Attacking others due to selfish needs. Making situations worse than they need to be. Causing drama as a way to assert yourself. Conversely, choosing your battles wisely. Not every injustice needs to be righted, by you, right now. Changing your perspective to see where you have been in the wrong, where you have been the aggressor unnecessarily, perhaps to find a fairer way to relate to others. Acting against your own interests due to pride. One wolf attacks another, not understanding that htey are the same. Deciding to relate to others in a kinder way."},
    {name: "Six Of Swords", img: "Six Of Swords", description: "Transition. Can describe a dark moment, as the light on the other end might not be seen yet. An in-between moment, which can feel uncomfortable in its ambiguity. Travelling - from one place to another, from one relatinship to another, from one life to another. A temporary situation. A swan, a symbol of transformation, swims from one bank to another, while butterflies, another symbol of transformation, fly in a downward formation abover her. Change is inevitable and nevessary but not always easy. Accepting assistance from others during this time, a need to be gentle on yourself whenever movement is required."},
    {name: "Seven Of Swords", img: "Seven Of Swords", description: "A poison pen, words meant to sting. Gossip. Being sneaky. Using strategy or manipulation. Only looking out for number one - or being in a tricky situation where you need to think of yourself first. Extracting yourself from drama - or playing into the drama. Outwitting someone. Being pollitical in your interactions. A hand tests out the sharpness of an arrow while a snake looks on. Six more arrows are ready and waiting. Words are weapons when used intentionally against another person."},
    {name: "Eight Of Swords", img: "Eight Of Swords", description: "Feeling trapped in a situations, and not seeing a way out. Letting other people's actions or perspectives dominate your own way of being, rather than working from an internal strength or intuition. Frustration at a situation. Feelings of helplessness that keep you from seeing your own agency. Flies are trapped in the spider's web, although the are not yet killed. Pessimistic thoughts, making a bad situation worse by allowing external forces to gain power over you. A need to open your eyes to see where you do have freedom to move."},
    {name: "Nine Of Swords", img: "Nine Of Swords", description: "Anxiety. Regret. Being chained to the past by your thought patterns. Unacknowledged, unspoken fears. Burdening yourself with your thoughts, but unable to take action. Feeling tied to the past. Rumination. A need to release old habits and thoughts in order to be lighter and freer. A pile of skulls intertwines with chains and cobwebs. An emotional house cleaning is needed. Stagnation turns to despair, darkens your soul. A need to face your fears in order to become untroubled, unburdened."},
    {name: "Ten Of Swords", img: "Ten Of Swords", description: "The end of a cycle. Beating a dead horse. Lingering pain. Time to move on, prologing the inevitable. Having an exaggerated response to a conflict. Bringing up old pain and suffering in order to heal from it. A healing crisis. A snake, which normally sheds his skin, is cut up into pieces by box cutters. Needing to evolve or move on, but being so resistant to transofmation that drastic events have to occur to move your forward. A wake-up call. Rock bottom."}, 
    {name: "Page Of Swords", img: "Page Of Swords", description: "New ideas, thoughts, mental paradigms. Getting assistance from others to figure out a new solution to a problem. When someone opens your eyes to a different perspective. Being able to re-wirte a senario. Turning over a new leaf in your personality, learning a new skill. A hand holds open a book with only one letter, the rest to be written."},
    {name: "Knight Of Swords", img: "Knight Of Swords", description: "Taking action with a clear mind. Being supported by facts and logic. Allowing your thoughts to lead the way - rushing ahead. Getting ahead of yourself, jumping to conclusions. In order to take right action, balance is needed between your idea of things and the reality of things. When this occurs, it's like a puzzle piece fitting into place. If not, it's more like a dagger forced into place."},
    {name: "Queen Of Swords", img: "Queen Of Swords", description: "A smart, sharp woman. Not nurtuing but still supportive. Can be cold and with a cutting tongue, can be a leader and a boss. Reliable even if distant. Solitary and unemotional, good at business and logistics. Uses her words to get ahead or to tear down others. Uses her head more than her heart, a savvy business woman."},
    {name: "King Of Swords", img: "King Of Swords", description: "An authoritative figure. The man in charge. Does not show his emotions or vulnerability. Someone who is emotionally unavailable or inaccessible. A wit, good with words. Understands how the worlds of inance, science, politics work - less about how internal feelings work. Someone with walls up, who enjoys eliciting fear or respect from others."},
    {name: "Ace Of Wands", img: "Ace Of Wands", description: "A spark. An idea that pops into your head. Allowing imagination to run wild. Excitement about something just beginning. A creative energy that will grow to be much larger. Only one match is lit, but it could easily spread to the rest of the matchbook. Contagious creativity."},
    {name: "Two Of Wands", img: "Two Of Wands", description: "Uncertainty. Feeling overwhelmed, having many options. Open space ahead. Many possibilities, multiple paths open to you. Allowing chance to lead you. Throwing the dice allows a conversation and an interaction between you and the world around you. Seeing how what feels like 'too many options' can be narrowed down once you factor in external circumstances. Pinning down what's really possible."},
    {name: "Three Of Wands", img: "Three Of Wands", description: "Aiming for your future. Having a dream and working towards it, even if you're still at the starting gate. Thinking big. Allowing for growth and expansion from the outset. Being single-minded about your goals. Covering all your bases while keeping the end result in mind. The image of the hand throwing darts shows all aspects necessary for hitting your mark: aiming true, forward momentum, hitting the bullseye."},
    {name: "Four Of Wands", img: "Four Of Wands", description: "Having a good foundation. An extermanl structure that supports emotional well-being. Joy that comes from feling secure. The start of a house of cards has been built, a solid foundation of 4 of clubs. A bejeweled hand reaches down, satified with what has been built so far. Doing something that makes you happy. Work that sustains you creatively."}, 
    {name: "Five Of Wands", img: "Five Of Wands", description: "Dynamic energy that can feel chaotic, or constructive. Working with other people's needs, making a decision to bulldoze over them or to take htem into consideration. Working in a group situationwith lots of opinions and desires. Group dynamics. Five hands are holding pool cues, all trying to hit their billiard balls at once. Having to figure out a cohesive way to make things work for all, or it won't work for anyone."},
    {name: "Six Of Wands", img: "Six Of Wands", description: "Receiving praise and accolades from others. Feeling satisfied with your achievements but also seeing others' satisfaction as well. Being cheered on. Support from others. Success. Being humble when winning. Including others in your triumphs. The reciprocity of the performer and the audience. A basketball shot is made under the canopy of gladiolas -- a symbol of the gladiator, who performed feats of strength for the entertainment of others."},
    {name: "Seven Of Wands", img: "Seven Of Wands", description: "Assertion of the self. Accomplishment. Overcoming obstacles to come out on top. Sticking to you convictions. Working on achieving your goals. A cat jumps over seven burning candles, both a trick and the natural ability of a graceful animal. Being able to remain calm in a challenging situation. Grace under pressure."},
    {name: "Eight Of Wands", img: "Eight Of Wands", description: "Things happening fast. A domino effect. Using momentum to your benefit, seeing opportunites. A row of matches burns quickly. Spreading excitement. Taking advantage of the moment. Now or never. An opportunity to bring out certain skills you have waiting in your toolbox."},
    {name: "Nine Of Wands", img: "Nine Of Wands", description: "Dust yourself off and try again. When energy flags but there is more in reserve. Almost there. Believing in yourself despite a setback. Not allowing the past to dictate how you move forward. Waiting. Replenishing energy into a project or a mission or a belief. A breakthrough. Making it happen last minute. Rediscovering your passion for something that had become stale. The candle burns down but rises again once the hand re-emerges to re-light it."},
    {name: "Ten Of Wands", img: "Ten Of Wands", description: "An excesss of energy. Creativity let out of bounds. When your dream becomes reality but ti's too much for one person. All of the cards are shown with snakes breaking through, disrupting and keeping them from their original purpose. Excitement that clouds vision. A need to rein it in a little, or to dole out some responsibility to others."},
    {name: "Page Of Wands", img: "Page Of Wands", description: "A hand holds a royal flush. Recognizing your skills and gifts, and using them wisely -- or accepting help from someone else's skills and gifts. A good thing coming into your life, good news. An aspect of your life becoming more exciting. Embodying the winning energy as part of your plan to achieve your goals. Seeing, and believing, the positive."},
    {name: "Knight Of Wands", img: "Knight Of Wands", description: "Taking action in a daring way. Looking for excitement. Ready to take a risk. Playing with fire. Being open to miracles or serendipity. The roll of the dice and the dancing dragons show a playful energy where anything is possible."},
    {name: "Queen Of Wands", img: "Queen Of Wands", description: "A creative, ecccentric woman. Fun, playful, warm, caring, encouraging. Her strength comes from her quickness, her embrace of the new. Giving to others, but maintains her own practices of self-care and self-exploration. Likes to laugh and enjoys herself and others. Proud, strong, and with a light inside."},
    {name: "King Of Wands", img: "King Of Wands", description: "An artistic man. Can be unreliable or hard to pin down, but charming and exciting to be around. Not very practical or conventional, but passionate. Can get himself into trouble through inactions, or taking the wrong action. Has a good heart but not the best instincts about himself of the people around him. Mischievous and quick-witted. Always up for a good time, but can be hiding some pain inside."},









])
